### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by Honoki018** [luzexi/Unity3D-bluetooth#1]
hello. thank you for the plugins.
i'm just a beginner in unity and i wanna try making an android board game that will use bluetooth connection to connect with another android device to play with. is it possible to use this plugin?
and if it can, how can i use it? don't this have a documentation or tutorial? or even examples how it works?

**Comment by luzexi** [comment]
You know unity3d asset store right?
This plugin is from https://www.assetstore.unity3d.com/cn/#!/content/26661
The demo you can download from http://pan.baidu.com/s/1mgJ7daC in chinese.

**Comment by luzexi** [comment]
This plugins of author is not me. I buy it in unity3d store. So~ You know. Be careful.
